//auth
export const AUTH_SIGN_IN = "AUTH_SIGN_IN";
export const AUTH_SIGN_OUT = "AUTH_SIGN_OUT";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const INCREASE_HMT_COUNT = "INCREASE_HMT_COUNT";
export const DECREASE_HMT_COUNT = "DECREASE_HMT_COUNT";
export const SET_CAPTCHA_TOKEN = "SET_CAPTCHA_TOKEN";
