export const errorType = {
  invaidPassword: 'invalidPassword',
  invalidEmail: 'invalidEmail',
  invalidWalletAddress: 'invalidWalletAddress',
  duplicatedEmail: 'duplicatedEmail',
  duplicatedUserName: 'duplicatedUserName',
  requireUserName: 'requireUserName',
  requireFirstName: 'requireFirstName',
  requireLastName: 'requireLastName',
  requirePassword: 'requirePassword',
  requireEmail: 'requireEmail',
  requireWalletAddress: 'requireWalletAddress',
};

export const errorMessage = {
  invalidPasswordLength: 'Password must be at least 8 characters',
  invalidWalletAddress: 'Invalid Wallet Address',
  invalidLengthWalletAddress: 'Wallet Address length must be 42',
  invalidEmail: 'Invalid Email',
  duplicatedEmail: 'Email is already used',
  requirePassword: 'Password required',
  requireEmail: 'Email required',
  requireUserName: 'User name required',
  requireWalletAddress: 'Wallet Address required',
  requireVerificationToken: 'Verification token required',
  invalidVerificationToken: 'Invalid verification token',
  captchaPassRequired: 'You need to solve captcha',
  requireCountry: 'Country required',
  notConfirmedPassword: 'Passwords should be same',
  requireRestPasswordToken: 'Verification token required',
  requireAuthToken: 'Authentication token required',
  requireProfileDetails: 'Profile details required',
  sactionListError: 'The app is not available in your location. Please refer to our T&Cs',
  requiredWithdrawAmount: 'Amount required',
  invalidWithdrawAmount: 'Amount should be positive float value',
};
