name: Docker build

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Build image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # - name: Configure AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: ap-south-1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::340792883311:role/GithubActionsRoleECR
        role-session-name: GithubActionsSession
        aws-region: eu-west-1
      if: github.event_name != 'pull_request'

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      if: github.event_name != 'pull_request'

    # - name: Check envs
    #   id: check_envs
    #   run: |
    #     echo $GITHUB_REF_NAME
    #     echo ${GITHUB_SHA::7}

    - name: Build the image
      id: build-image
      if: github.event_name == 'pull_request'
      run: |
        docker build -f Dockerfile .

    - name: Build and push the image to Amazon ECR
      id: build-push-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: human-app-ui
      if: github.event_name != 'pull_request'
      run: |
        export IMAGE_TAG=$GITHUB_REF_NAME-${GITHUB_SHA::7}-$(date +%s)
        docker build $(for i in `cat build.args`; do out+="--build-arg $i " ; done; echo $out;out="") -t $ECR_REGISTRY/$ECR_REPOSITORY:${IMAGE_TAG} -f Dockerfile .
        echo "Pushing image to ECR..."
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:${IMAGE_TAG}
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:${IMAGE_TAG}"
