name: Docker build

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Build image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # - name: Configure AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: ap-south-1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::340792883311:role/GithubActionsRoleECR
        role-session-name: GithubActionsSession
        aws-region: us-east-2
      if: github.event_name != 'pull_request'

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      if: github.event_name != 'pull_request'

    # - name: Check envs
    #   id: check_envs
    #   run: |
    #     echo $GITHUB_REF_NAME
    #     echo ${GITHUB_SHA::7}

    - name: Build the image
      id: build-image
      if: github.event_name == 'pull_request'
      run: |
        docker build -f Dockerfile .

    - name: Build and push the develop image to Amazon ECR
      id: build-push-image-develop
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: human-app-ui
      if: github.ref == 'refs/heads/develop'
      run: |
        export IMAGE_TAG=$GITHUB_REF_NAME-${GITHUB_SHA::7}-$(date +%s)
        docker build \
          --build-arg REACT_APP_API_URL="http://ec2-18-220-126-12.us-east-2.compute.amazonaws.com:3000/v1" \
          --build-arg REACT_APP_HCAPTCHA_SITE_KEY="c8e519a2-032a-4e45-9bf1-4f10f6af1b1f" \
          --build-arg REACT_APP_CIVIC_APP_ID="9CXmtYJvd" \
          -t $ECR_REGISTRY/$ECR_REPOSITORY:${IMAGE_TAG} -f Dockerfile .
        echo "Pushing image to ECR..."
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:${IMAGE_TAG}
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:${IMAGE_TAG}"
        echo "image_tag=${IMAGE_TAG}" >> $GITHUB_ENV

    - name: Build and push the master image to Amazon ECR
      id: build-push-image-master
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: human-app-ui
      if: github.ref == 'refs/heads/master'
      run: |
        export IMAGE_TAG=$GITHUB_REF_NAME-${GITHUB_SHA::7}-$(date +%s)
        docker build \
          --build-arg REACT_APP_API_URL="https://api.humanprotocol.org/v1" \
          --build-arg REACT_APP_HCAPTCHA_SITE_KEY="10cd757e-a469-4302-9ee2-a89e024da91a" \
          --build-arg REACT_APP_CIVIC_APP_ID="9CXmtYJvd" \
          -t $ECR_REGISTRY/$ECR_REPOSITORY:${IMAGE_TAG} -f Dockerfile .
        echo "Pushing image to ECR..."
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:${IMAGE_TAG}
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:${IMAGE_TAG}"
        echo "image_tag=${IMAGE_TAG}" >> $GITHUB_ENV

    - name: Execute a script throuh SSM Run Command on Staging
      id: execute-script-staging
      env:
        INSTANCE_IDS: "i-04772cfd99decdcb3"
      if: github.ref == 'refs/heads/develop'
      run: |
        export IMAGE_TAG="${{ env.image_tag }}"
        .github/workflows/common/ssm_run_script.sh
